env:
  browser: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: vue-eslint-parser
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: 2018
  sourceType: module
  project: './tsconfig.json'
  extraFileExtensions:
    - vue
plugins:
  - 'vue'
  - '@typescript-eslint'
rules:
  max-len: [error, 120]
  require-jsdoc: off
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars-experimental':
    - error
    - ignoreArgsIfArgsAfterAreUsed: true
  arrow-parens:
    - error
    - as-needed
  indent:
    - error
    - 2
    - CallExpression:
        arguments: 1
      SwitchCase: 1
  new-cap:
    - error
    - capIsNewExceptions:
        - Component
  no-console:
    - error
    - allow:
        - debug
        - warn
        - error
  no-debugger: error
  quotes:
    - error
    - 'single'
    - allowTemplateLiterals: true
      avoidEscape: true

overrides:
  - files: ['*.vue']
    rules:
      indent: off
      vue/script-indent:
        - error
        - 2
        - baseIndent: 1
          switchCase: 1
